In [75]:
import os
import ast
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.width', 1000)

from tqdm import tqdm

from openai import AzureOpenAI

pd.set_option('display.max_columns', 100)

### Load OpenAI Model

In [76]:
os.environ["AZURE_OPENAI_KEY"] = "d5b2af9699e1475fbaaf9dfb97aad739"
os.environ["AZURE_OPENAI_ENDPOINT"] = "https://bloktrek-azure-openai-instance.openai.azure.com/"
os.environ["AZURE_API_VERSION"] = "2023-08-01-preview"
os.environ["AZURE_DEPLOYMENT_ID"] = "gpt-4o-mini-dep1"
os.environ["AWS_ACCESS_KEY"] = "ASIAWLOG2ZPM73OFJD6U"
os.environ["AWS_SECRET_KEY"] = "Xc0bSBpsg/8DRVPkTgshO4K+oJKKpcLAgf4m30lk"
os.environ["AWS_SESSION_TOKEN"] = "IQoJb3JpZ2luX2VjEFkaCXVzLWVhc3QtMSJHMEUCIC/XQkRVv7/MCNiVJD8PLto6MPP8VGgYtv3UBVLGkR6lAiEA9acahZyew2T8ntkdiXZmE5ysxzhKB6cw0x5VgdwaYMwqlgMIQhAAGgw0MzY4OTMwNDM2NzMiDP+TuoFZjuMPCgvZdSrzAofMBpfYhh2hoKhsSZ54jKM+xLo+If9mP7plTnx5aaa06rccPmCWLXnct8c8q3IXyj1AsQAHW488ZCe2W+/pi7Tl3W5JK+loPOK4cg5NdZ4nXzuVNoJLSBw3ZMGSelWZZcIeMohhM4Q3fyEf1U7TvLaa0ujZD+1csa+PweIgBG7m2/AgqtdrQb4BXShnB5xIiBtnvbAHzghAPF8oz9p7wRwuJmg68wgAYstDN+gSBm4FaWe/S34LyD8z051QTZDpx+P//dqsTR6VNW+eNxXuNp5HkhPTUuzJqdB//EiwZEpkHzeyHEgRGBtRsJ9VjP2DwI8sXgXEvnNYiPpBRO1i15r4CgVRImt43PmNO2KpbhXzR41cQufZcPTA8al8zzYiG+I8GUdFSh+2mth1z3p/MQFedzoUM0gZqjbRb3ogV814LH5KO6p3JK5PkqLxYgO2QQ4Nn8TMuBTe8lIGOI8CI+3NkjEyVROvm3/IpuuPCJlTuHc0MN3OorUGOqYBu44c5HhhBJShyTGJzufu15qtU0SDahPpqaEWD3lvT+mGmX0wcXuzwg25M1dfbabRa3O8CXBjzQBHuAcfFsJdy1sRuJVKKVXGkJUGeY37O72odPGNixa8DmONdu2F7RfwGvWRhFOc+Yi6PwaOs7UxLBbSqjgxQtIL3pZ2D+H1EuT5pSTCHD1oeUO4jz0MP7mXDtavubGBet48j9uPiJSmDypl+hnMfQ=="
os.environ["AWS_REGION"] = "ap-south-1"
model_name = "gpt-4o-mini"

client = AzureOpenAI(
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_KEY"),
    api_version=os.getenv("AZURE_API_VERSION"),
    azure_deployment=os.getenv("AZURE_DEPLOYMENT_ID")
)

### Taxonomy Functions

In [77]:
def clean_and_parse(x):
    import ast 

    if isinstance(x, str) and x.startswith('[') and x.endswith(']'):
        cleaned = x.replace('""', '"')
        cleaned = cleaned.replace('\n', ' ').replace('\r', '')  # Remove line breaks, if any

        try:
            return ast.literal_eval(cleaned)
        except Exception as e:
            print(f"Error parsing string: {cleaned}\n{e}")
            return x
    else:
        return x

def get_main_taxonomy_examples(dom: str, mode: str) -> str:

    if mode == "CC":
    
        df = pd.read_csv("../semeval-task-10/cc_taxonomy.csv")
        df = df.astype(str)
        df['Main Narrative Example'] = df['Main Narrative Example'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') and x.endswith(']') else x)
                
        taxonomy = ''
        examples = ''

        dom = dom.split(":")[0] if len(dom.split(":")) > 0 else dom

        if dom in df['Main Narrative'].values:
            temp = df[df['Main Narrative'] == dom].reset_index()         
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Main Narrative']} | Definition: {temp.loc[0, 'Main Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Main Narrative Example'], list):
                for item in temp.loc[0, 'Main Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Main Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Main Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Main Narrative']}\n"
            else:
                pass


        return (taxonomy, examples)

    else:

        df = pd.read_csv("../semeval-task-10/urw_taxonomy.csv")
        df = df.astype(str)
        df['Main Narrative Example'] = df['Main Narrative Example'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') and x.endswith(']') else x)
          
        taxonomy = ''
        examples = ''

        dom = dom.split(":")[0] if len(dom.split(":")) > 0 else dom

        if dom in df['Main Narrative'].values:
            temp = df[df['Main Narrative'] == dom].reset_index()           
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Main Narrative']} | Definition: {temp.loc[0, 'Main Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Main Narrative Example'], list):
                for item in temp.loc[0, 'Main Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Main Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Main Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Main Narrative']}\n"
            else:
                pass
            
        return (taxonomy, examples)

def get_sub_taxonomy_examples(sub: str, mode: str) -> str:

    if mode == "CC":
        df = pd.read_csv("../semeval-task-10/cc_taxonomy.csv")
        df = df.astype(str)
        df['Sub Narrative Example'] = df['Sub Narrative Example'].apply(clean_and_parse)

        taxonomy = ''
        examples = ''

        sub = sub.split(":")[2][1:] if len(sub.split(":")) > 1 else sub

        if sub in df['Sub Narrative'].values:
            temp = df[df['Sub Narrative'] == sub].reset_index()
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Sub Narrative']} | Definition: {temp.loc[0, 'Sub Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Sub Narrative Example'], list):
                for item in temp.loc[0, 'Sub Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Sub Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Sub Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Sub Narrative']}\n"
            else:
                pass
        return (taxonomy, examples)

    else:
        df = pd.read_csv("../semeval-task-10/urw_taxonomy.csv")
        df = df.astype(str)
        df['Sub Narrative Example'] = df['Sub Narrative Example'].apply(clean_and_parse)

        taxonomy = ''
        examples = ''

        sub = sub.split(":")[2][1:] if len(sub.split(":")) > 1 else sub

        if sub in df['Sub Narrative'].values:
            temp = df[df['Sub Narrative'] == sub].reset_index()
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Sub Narrative']} | Definition: {temp.loc[0, 'Sub Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Sub Narrative Example'], list):
                for item in temp.loc[0, 'Sub Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Sub Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Sub Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Sub Narrative']}\n"
            else:
                pass
        return (taxonomy, examples)

In [78]:
def create_prompt(text, dom, sub, mode):
    # Helper function replacing quotation marks in the text:
    replace_qm = lambda s: s.replace('"', "'")

    language = 'RUSSIAN'

    if mode == "CC":
        # Update predicted_labels by slicing from the 4th character
        main_taxonomy, main_examples = get_main_taxonomy_examples(dom, mode)
        sub_taxonomy, sub_examples = get_sub_taxonomy_examples(sub, mode)
        context = f"""You will be given an article along with the dominant narrative and sub narrative associated with the article. 
        
        GOAL: Justify the choice of dominant and sub narratives assigned to the article in {language}. Provide reasoning and quote relevant text from the original text as to why these are the correct choice of dominant and sub narratives for the text file.

            INSTRUCTIONS:
            Read the provided text carefully.
            You will be given: 
            1.Taxonomy - definition of the narrative
            2.List of relevant examples - sentences which determine which justify the narrative and align with its defintion 
            3.Any additional idenyifying information for the narratives.
            Based on the given information give an explanation as to why the dominant and sub narratives are the correct choice for the text file.
            
            Note: Keep the output concise and to the point - ideally find relevant textual examples.

            DOMINANT NARRATIVE: {dom[4:]}
            TAXONOMY: {main_taxonomy}
            RELEVANT EXAMPLES: 
            {main_examples}

            SUB NARRATIVE: {sub[4:]}
            TAXONOMY: {sub_taxonomy}
            RELEVANT EXAMPLES:
            {sub_examples}
        """

        prompt = f'''{context}
        -------------------------------------------------------
        Based on the given Instructions, Taxonomies and Examples: Justify the choice of dominant and sub narratives assigned to the Climate Change article in {language} within 80 words.

        ARTICLE TEXT TO PREDICT: "{replace_qm(text)}" => '''
        
        return {
            "role": "user",
            "content": prompt
        }
        
    else:
        # Update predicted_labels by slicing from the 5th character
        main_taxonomy, main_examples = get_main_taxonomy_examples(dom, mode)
        sub_taxonomy, sub_examples = get_sub_taxonomy_examples(sub, mode)

        context = f"""You will be given an article along with the dominant narrative and sub narrative associated with the article. 
        
        GOAL: Justify the choice of dominant and sub narratives assigned to the article in {language}. Provide reasoning and quote relevant text from the original text as to why these are the correct choice of dominant and sub narratives for the text file.

            INSTRUCTIONS:
            Read the provided text carefully.
            You will be given: 
            1.Taxonomy - definition of the narrative
            2.List of relevant examples - sentences which determine which justify the narrative and align with its defintion 
            3.Any additional idenyifying information for the narratives.
            Based on the given information give an explanation as to why the dominant and sub narratives are the correct choice for the text file.
            
            Note: Keep the output concise and to the point - ideally find relevant textual examples.

            DOMINANT NARRATIVE: {dom[4:]}
            TAXONOMY: {main_taxonomy}
            RELEVANT EXAMPLES: 
            {main_examples}

            SUB NARRATIVE: {sub[4:]}
            TAXONOMY: {sub_taxonomy}
            RELEVANT EXAMPLES:
            {sub_examples}
        """

        prompt = f'''{context}
        -------------------------------------------------------
        Based on the given Instructions, Taxonomies and Examples: Justify the choice of dominant and sub narratives assigned to the Climate Change article in {language} within 80 words.

        ARTICLE TEXT TO PREDICT: "{replace_qm(text)}" => '''
        
        return {
            "role": "user",
            "content": prompt
        }

In [79]:
def get_embedded_json(embedded_str):
    import re
    try:
        # Extract only the list content using regex
        match = re.search(r"\[.*\]", embedded_str)
        if not match:
            return []  # Return empty list if no valid list is found
        
        cleaned_str = match.group(0)  # Extract the matched list portion

        # Convert to Python list safely
        return ast.literal_eval(cleaned_str)
    
    except (ValueError, SyntaxError):
        return []  # Return empty list if parsing fails

In [80]:
def generate_response_with_retries(text: str, dom, sub, mode, temp, retries=3, backoff_factor=0.5):
    language = 'RUSSIAN'

    system_main = f'''
You are an expert trained to analyse and justify the choice of dominant and sub narratives assigned to a given article within 80 words.

Instructions:
- Write in {language} only.
- Use ReACT (Reasoning and Contextual Text) to justify the choice of dominant and sub narratives assigned to the article.
- Provide reasoning and quote relevant text from the original text as to why these are the correct choice of dominant and sub narratives for the text file.
- Keep the output concise and to the point—ideally find relevant textual examples.

Categorization Rules:
- Use the help of the provided taxonomy and examples to justify the choice of dominant and sub narratives assigned to the article.

OUTPUT FORMAT:
- Return {language} language text in paragraph(s) format within 80 words.
'''

    prompt = create_prompt(text, dom, sub, mode)
    messages = [
        {"role": "system", "content": system_main},
        {"role": "user", "content": prompt.get("content", "")}
    ]

    # Retry mechanism with exponential backoff
    for attempt in range(1, retries + 1):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                temperature=temp,
                max_tokens=100
            )
            output = str(response.choices[0].message.content)
            return output  # Return the response if successful

        except (openai.error.Timeout, openai.error.APIError, openai.error.RateLimitError) as e:
            print(f"Attempt {attempt} failed with error: {e}")
            
            if attempt < retries:
                # Exponential backoff
                sleep_time = backoff_factor * (2 ** (attempt - 1))
                print(f"Retrying in {sleep_time} seconds...")
                time.sleep(sleep_time)
            else:
                print(f"Failed after {retries} attempts.")
                return f"Error: {e}"

        except Exception as e:
            # Catch unexpected errors
            print(f"Unexpected error: {e}")
            return f"Unexpected Error: {e}"

### Importing the data

In [81]:
df = pd.read_csv('/Users/rahulbouri/Downloads/SemEval 2025 Test Data/RU_test_data.csv')

In [82]:
df.shape

(56, 4)

In [83]:
df.head()

        article_id                     dominant_narrative                                     sub_narratives                                               text
0  RU-URW-1207.txt  URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  Юбилейный саммит НАТО: за 75 лет провалов гора...
1  RU-URW-1232.txt                  URW: Praise of Russia  URW: Praise of Russia: Praise of Russian milit...  ﻿Российские штурмовики забросили мину в здание...
2  RU-URW-1292.txt                  URW: Praise of Russia                                               none  ﻿В сети можно найти много информации о том, чт...
3  RU-URW-1186.txt                  URW: Praise of Russia  URW: Praise of Russia: Praise of Russian milit...  Ужесточились бои в Донецкой области: потери ВС...
4  RU-URW-1224.txt  URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  Российские власти блокируют игры и стримы, соб...

In [84]:
df['mode'] = df['dominant_narrative'].apply(lambda x: 'CC' if x.split(':')[0] == 'CC' else 'URW')

In [85]:
df['mode'].value_counts()

mode
URW    56
Name: count, dtype: int64

In [86]:
df.head()

        article_id                     dominant_narrative                                     sub_narratives                                               text mode
0  RU-URW-1207.txt  URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  Юбилейный саммит НАТО: за 75 лет провалов гора...  URW
1  RU-URW-1232.txt                  URW: Praise of Russia  URW: Praise of Russia: Praise of Russian milit...  ﻿Российские штурмовики забросили мину в здание...  URW
2  RU-URW-1292.txt                  URW: Praise of Russia                                               none  ﻿В сети можно найти много информации о том, чт...  URW
3  RU-URW-1186.txt                  URW: Praise of Russia  URW: Praise of Russia: Praise of Russian milit...  Ужесточились бои в Донецкой области: потери ВС...  URW
4  RU-URW-1224.txt  URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  Российские власти блокируют игры и стримы, соб...  URW

In [87]:
# tqdm.pandas()

# for i in np.arange(0.1, 1, 0.1):
#     print("Iterating at temperature: ", i.round(2))
#     temp = i.round(2)
#     df[f'output_temp_{temp}'] = df.progress_apply(lambda x: generate_response(x['text'], x['dominant_narrative'], x['sub_narratives'], x['mode'], temp), axis=1)

# Enable tqdm progress bar for parallel processing
from concurrent.futures import ThreadPoolExecutor, as_completed
tqdm.pandas()

# Function to handle each API call
def process_row(row, temp):
    return generate_response_with_retries(row['text'], row['dominant_narrative'], row['sub_narratives'], row['mode'], temp)


# Function to process each temperature
def process_temperature(temp, df):
    temp = round(temp, 2)
    tqdm.write(f"Iterating at temperature: {temp}")

    # Use ThreadPoolExecutor for concurrent API calls
    with ThreadPoolExecutor(max_workers=25) as executor:
        futures = {executor.submit(process_row, row, temp): idx for idx, row in df.iterrows()}

        # Collect results with progress tracking
        results = []
        for future in tqdm(as_completed(futures), total=len(futures), desc=f'Temp {temp}'):
            idx = futures[future]
            try:
                result = future.result()
            except Exception as e:
                result = f"Error: {e}"  # Handle API errors gracefully
            results.append((idx, result))

    # Assign results back to DataFrame
    output_column = f'output_temp_{temp}'
    df[output_column] = pd.Series(dict(results))

    return df[[output_column]]


result = process_temperature(temp=0.3, df=df.copy())

df = pd.concat([df, result], axis=1)

Iterating at temperature: 0.3

Temp 0.3: 100%|██████████| 56/56 [00:13<00:00,  4.29it/s]

In [88]:
df.to_csv('/Users/rahulbouri/Downloads/SemEval 2025 Test Data/predictions/RU_data.csv', index=False)