In [1]:
import os
import ast
import numpy as np
import pandas as pd
from openai import AzureOpenAI
import chromadb.utils.embedding_functions as embedding_functions
import chromadb

pd.set_option('display.max_rows', 500)
pd.set_option('display.width', 1000)

from tqdm import tqdm

from openai import AzureOpenAI

pd.set_option('display.max_columns', 100)

### Load OpenAI Model

In [2]:
os.environ["AZURE_OPENAI_KEY"] = "d5b2af9699e1475fbaaf9dfb97aad739"
os.environ["AZURE_OPENAI_ENDPOINT"] = "https://bloktrek-azure-openai-instance.openai.azure.com/"
os.environ["AZURE_API_VERSION"] = "2023-08-01-preview"
os.environ["AZURE_DEPLOYMENT_ID"] = "gpt-4o-mini-dep1"
os.environ["AWS_ACCESS_KEY"] = "ASIAWLOG2ZPM73OFJD6U"
os.environ["AWS_SECRET_KEY"] = "Xc0bSBpsg/8DRVPkTgshO4K+oJKKpcLAgf4m30lk"
os.environ["AWS_SESSION_TOKEN"] = "IQoJb3JpZ2luX2VjEFkaCXVzLWVhc3QtMSJHMEUCIC/XQkRVv7/MCNiVJD8PLto6MPP8VGgYtv3UBVLGkR6lAiEA9acahZyew2T8ntkdiXZmE5ysxzhKB6cw0x5VgdwaYMwqlgMIQhAAGgw0MzY4OTMwNDM2NzMiDP+TuoFZjuMPCgvZdSrzAofMBpfYhh2hoKhsSZ54jKM+xLo+If9mP7plTnx5aaa06rccPmCWLXnct8c8q3IXyj1AsQAHW488ZCe2W+/pi7Tl3W5JK+loPOK4cg5NdZ4nXzuVNoJLSBw3ZMGSelWZZcIeMohhM4Q3fyEf1U7TvLaa0ujZD+1csa+PweIgBG7m2/AgqtdrQb4BXShnB5xIiBtnvbAHzghAPF8oz9p7wRwuJmg68wgAYstDN+gSBm4FaWe/S34LyD8z051QTZDpx+P//dqsTR6VNW+eNxXuNp5HkhPTUuzJqdB//EiwZEpkHzeyHEgRGBtRsJ9VjP2DwI8sXgXEvnNYiPpBRO1i15r4CgVRImt43PmNO2KpbhXzR41cQufZcPTA8al8zzYiG+I8GUdFSh+2mth1z3p/MQFedzoUM0gZqjbRb3ogV814LH5KO6p3JK5PkqLxYgO2QQ4Nn8TMuBTe8lIGOI8CI+3NkjEyVROvm3/IpuuPCJlTuHc0MN3OorUGOqYBu44c5HhhBJShyTGJzufu15qtU0SDahPpqaEWD3lvT+mGmX0wcXuzwg25M1dfbabRa3O8CXBjzQBHuAcfFsJdy1sRuJVKKVXGkJUGeY37O72odPGNixa8DmONdu2F7RfwGvWRhFOc+Yi6PwaOs7UxLBbSqjgxQtIL3pZ2D+H1EuT5pSTCHD1oeUO4jz0MP7mXDtavubGBet48j9uPiJSmDypl+hnMfQ=="
os.environ["AWS_REGION"] = "ap-south-1"
model_name = "gpt-4o-mini"

client = AzureOpenAI(
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_KEY"),
    api_version=os.getenv("AZURE_API_VERSION"),
    azure_deployment=os.getenv("AZURE_DEPLOYMENT_ID")
)

In [3]:

openai_ef = embedding_functions.OpenAIEmbeddingFunction(
                api_key=os.getenv("AZURE_OPENAI_KEY"),
                api_base=os.getenv("AZURE_OPENAI_ENDPOINT"),
                api_type="azure",
                api_version=os.getenv("AZURE_API_VERSION"),
                model_name="text-embedding-3-large"
            )

### Taxonomy Functions

In [4]:
def clean_and_parse(x):
    import ast 

    if isinstance(x, str) and x.startswith('[') and x.endswith(']'):
        cleaned = x.replace('""', '"')
        cleaned = cleaned.replace('\n', ' ').replace('\r', '')  # Remove line breaks, if any

        try:
            return ast.literal_eval(cleaned)
        except Exception as e:
            print(f"Error parsing string: {cleaned}\n{e}")
            return x
    else:
        return x

def get_main_taxonomy_examples(dom: str, mode: str) -> str:

    if mode == "CC":
    
        df = pd.read_csv("../semeval-task-10/cc_taxonomy.csv")
        df = df.astype(str)
        df['Main Narrative Example'] = df['Main Narrative Example'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') and x.endswith(']') else x)
                
        taxonomy = ''
        examples = ''

        dom = dom.split(":")[0] if len(dom.split(":")) > 0 else dom

        if dom in df['Main Narrative'].values:
            temp = df[df['Main Narrative'] == dom].reset_index()         
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Main Narrative']} | Definition: {temp.loc[0, 'Main Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Main Narrative Example'], list):
                for item in temp.loc[0, 'Main Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Main Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Main Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Main Narrative']}\n"
            else:
                pass


        return (taxonomy, examples)

    else:

        df = pd.read_csv("../semeval-task-10/urw_taxonomy.csv")
        df = df.astype(str)
        df['Main Narrative Example'] = df['Main Narrative Example'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') and x.endswith(']') else x)
          
        taxonomy = ''
        examples = ''

        dom = dom.split(":")[0] if len(dom.split(":")) > 0 else dom

        if dom in df['Main Narrative'].values:
            temp = df[df['Main Narrative'] == dom].reset_index()           
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Main Narrative']} | Definition: {temp.loc[0, 'Main Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Main Narrative Example'], list):
                for item in temp.loc[0, 'Main Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Main Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Main Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Main Narrative']}\n"
            else:
                pass
            
        return (taxonomy, examples)

def get_sub_taxonomy_examples(sub: str, mode: str) -> str:

    if mode == "CC":
        df = pd.read_csv("../semeval-task-10/cc_taxonomy.csv")
        df = df.astype(str)
        df['Sub Narrative Example'] = df['Sub Narrative Example'].apply(clean_and_parse)

        taxonomy = ''
        examples = ''

        sub = sub.split(":")[2][1:] if len(sub.split(":")) > 1 else sub

        if sub in df['Sub Narrative'].values:
            temp = df[df['Sub Narrative'] == sub].reset_index()
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Sub Narrative']} | Definition: {temp.loc[0, 'Sub Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Sub Narrative Example'], list):
                for item in temp.loc[0, 'Sub Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Sub Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Sub Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Sub Narrative']}\n"
            else:
                pass
        return (taxonomy, examples)

    else:
        df = pd.read_csv("../semeval-task-10/urw_taxonomy.csv")
        df = df.astype(str)
        df['Sub Narrative Example'] = df['Sub Narrative Example'].apply(clean_and_parse)

        taxonomy = ''
        examples = ''

        sub = sub.split(":")[2][1:] if len(sub.split(":")) > 1 else sub

        if sub in df['Sub Narrative'].values:
            temp = df[df['Sub Narrative'] == sub].reset_index()
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Sub Narrative']} | Definition: {temp.loc[0, 'Sub Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Sub Narrative Example'], list):
                for item in temp.loc[0, 'Sub Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Sub Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Sub Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Sub Narrative']}\n"
            else:
                pass
        return (taxonomy, examples)

In [5]:
def create_prompt(res, dom, sub, mode):
    # Helper function replacing quotation marks in the text:


    if mode == "CC":
        # Update predicted_labels by slicing from the 4th character
        main_taxonomy, main_examples = get_main_taxonomy_examples(dom, mode)
        sub_taxonomy, sub_examples = get_sub_taxonomy_examples(sub, mode)
        context = f"""You will be given the dominant narrative and sub narrative associated with an article along with a list of sentences supporting the dominant narrative from the article.
        
        GOAL: Justify the choice of dominant and sub narratives assigned to the article using the sentences given to you. Provide reasoning and quote relevant text from the original ssentences as to why these are the correct choice of dominant and sub narratives for the article using the list of sentences given to you.

            INSTRUCTIONS:
            Read the provided text carefully.
            You will be given: 
            1.Taxonomy - definition of the narrative
            2.Any additional idenyifying information for the narratives.
            Based on the given information give an explanation as to why the dominant and sub narratives are the correct choice for the article using the list of sentences given to you.
            
            Note: Keep the output concise and to the point - use relevant textual examples directly from the list of sentences given.

            DOMINANT NARRATIVE: {dom[4:]}
            TAXONOMY: {main_taxonomy}

            SUB NARRATIVE: {sub[4:]}
            TAXONOMY: {sub_taxonomy}
        """

        prompt = f'''{context}
        -------------------------------------------------------
        Based on the given Instructions and Taxonomies: Justify the choice of dominant and sub narratives assigned to the Climate Change article using the given list of sentences supporting the dominant narrative taken fron the article. 

        Output Format: Return text in paragraph format in strictly 75 words or under. Focus on quoting sentences directly.

        LIST OF SENTENCES SUPPORTING DOMINANT NARRATIVE FROM ARTICLE: "{res}" => '''
        
        return {
            "role": "user",
            "content": prompt
        }
        
    else:
        # Update predicted_labels by slicing from the 5th character
        main_taxonomy, main_examples = get_main_taxonomy_examples(dom, mode)
        sub_taxonomy, sub_examples = get_sub_taxonomy_examples(sub, mode)

        context = f"""You will be given the dominant narrative and sub narrative associated with an article along with a list of sentences supporting the dominant narrative from the article.
        
        GOAL: Justify the choice of dominant and sub narratives assigned to the article using the sentences given to you. Provide reasoning and quote relevant text from the original ssentences as to why these are the correct choice of dominant and sub narratives for the article using the list of sentences given to you.

            INSTRUCTIONS:
            Read the provided text carefully.
            You will be given: 
            1.Taxonomy - definition of the narrative
            2.Any additional idenyifying information for the narratives.
            Based on the given information give an explanation as to why the dominant and sub narratives are the correct choice for the article using the list of sentences given to you.
            
            Note: Keep the output concise and to the point - use relevant textual examples directly from the list of sentences given.

            DOMINANT NARRATIVE: {dom[4:]}
            TAXONOMY: {main_taxonomy}

            SUB NARRATIVE: {sub[4:]}
            TAXONOMY: {sub_taxonomy}
        """

        prompt = f'''{context}
        -------------------------------------------------------
        Based on the given Instructions and Taxonomies: Justify the choice of dominant and sub narratives assigned to the Ukraine Russia War article using the given list of sentences supporting the dominant narrative taken fron the article. 
        Output Format: Return text in paragraph format in strictly 75 words or under. Focus on quoting sentences directly.

        LIST OF SENTENCES SUPPORTING DOMINANT NARRATIVE FROM ARTICLE: "{res}" => '''
        
        return {
            "role": "user",
            "content": prompt
        }

In [6]:
def get_embedded_json(embedded_str):
    import re
    try:
        # Extract only the list content using regex
        match = re.search(r"\[.*\]", embedded_str)
        if not match:
            return []  # Return empty list if no valid list is found
        
        cleaned_str = match.group(0)  # Extract the matched list portion

        # Convert to Python list safely
        return ast.literal_eval(cleaned_str)
    
    except (ValueError, SyntaxError):
        return []  # Return empty list if parsing fails

In [7]:
import time
import random
from azure.core.exceptions import ServiceRequestError, AzureError

def add_documents_with_retry(collection, documents, ids, max_retries=40):
    assert len(documents) == len(ids), "The number of documents must match the number of IDs."

    for i, (doc, doc_id) in enumerate(zip(documents, ids)):
        retries = 0
        while retries <= max_retries:
            try:
                collection.add(documents=[doc], ids=[doc_id])
                if i%100==0:
                  print(f"Document {i + 1}/{len(documents)} added successfully.")
                break
            except AzureError as e:
                if "rate limit" in str(e).lower() or isinstance(e, ServiceRequestError):
                    retries += 1
                    wait_time = 2 ** retries + random.uniform(0, 1)
                    print(f"Rate limit exceeded. Retrying in {wait_time:.2f} seconds... (Attempt {retries}/{max_retries})")
                    time.sleep(wait_time)
                else:
                    print(f"Failed to add document {i + 1}: {e}")
                    break
            except Exception as e:
                print(f"An unexpected error occurred while adding document {i + 1}: {e}")
                break
        else:
            print(f"Exceeded maximum retries for document {i + 1}. Skipping...")

In [8]:
def split_and_retrieve_sentences(text: str, narrative: str, subnarrative: str, threshold: float):
    sentences = [s.strip() for s in text.replace('\n', '').split('.') if s.strip()]
    chroma_client = chromadb.Client()
    collection = chroma_client.create_collection(name="text-embedding-3-large", embedding_function=openai_ef, metadata={"hnsw:space": "cosine"})
    ids = [f"sentence_{i}" for i in range(len(sentences))]

    add_documents_with_retry(collection=collection, documents=sentences, ids=ids, max_retries=10)
    
    search_results = collection.query(
        query_texts=[narrative],
        n_results=5
    )
    top_documents = search_results['documents'][0].copy()
    top_scores = [1 - distance for distance in search_results['distances'][0]].copy()

    sub_search_results = collection.query(
        query_texts=[subnarrative],
        n_results=5
    )
    
    # Check if any result exceeds the threshold and add to search_results
    for doc, score, doc_id in zip(sub_search_results['documents'][0], sub_search_results['distances'][0], sub_search_results['ids'][0]):
        if 1 - score > threshold:
            # Add to search results if score exceeds the threshold
            top_documents.append(doc)
            top_scores.append(score)
            
    chroma_client.delete_collection("text-embedding-3-large")

    docs_df = pd.DataFrame({"document":top_documents, "score":top_scores})

    docs_df = docs_df.sort_values(by='score', ascending=False).reset_index(drop=True)

    top_docs = docs_df['document'].to_list()

    return top_docs

In [9]:
def generate_response(text:str, dom, sub, mode, temp):
    system_main = \
'''You are an expert trained to analyse and justify the choice of dominant and sub narratives assigned to a given article within 80 words.

Instructions:

Use ReACT (Reasoning and Contextual Text) to justify the choice of dominant and sub narratives assigned to the article.
Provide reasoning and quote relevant text from the original text as to why these are the correct choice of dominant and sub narratives for the text file.
Keep the output concise and to the point—ideally find relevant textual examples.

Categorization Rules:

Use the help of the provided taxonomy and examples to justify the choice of dominant and sub narratives assigned to the article.

OUTPUT FORMAT:
Return text in paragraph(s) format within 80 words.
'''

    relevant_sentences = split_and_retrieve_sentences(text, dom, sub, 0.25)
    
    prompt = create_prompt(relevant_sentences, dom, sub, mode)

    messages = [
        {"role": "system", "content": system_main},
        {"role": "user", "content": prompt.get("content", "")}
    ]
    
    response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=messages,
    temperature=temp,
    max_tokens=100
    )   

    output = str(response.choices[0].message.content)
    return output

def generate_response_with_retries(text: str, dom, sub, mode, temp, retries=3, backoff_factor=0.5):
    system_main = \
'''You are an expert trained to analyse and justify the choice of dominant and sub narratives assigned to a given article within 80 words.

Instructions:

Use ReACT (Reasoning and Contextual Text) to justify the choice of dominant and sub narratives assigned to the article.
Provide reasoning and quote relevant text from the original text as to why these are the correct choice of dominant and sub narratives for the text file.
Keep the output concise and to the point—ideally find relevant textual examples.

Categorization Rules:

Use the help of the provided taxonomy and examples to justify the choice of dominant and sub narratives assigned to the article.

OUTPUT FORMAT:
Return text in paragraph(s) format within 80 words.
'''

    relevant_sentences = split_and_retrieve_sentences(text, dom, sub, 0.25)
    
    prompt = create_prompt(relevant_sentences, dom, sub, mode)

    messages = [
        {"role": "system", "content": system_main},
        {"role": "user", "content": prompt.get("content", "")}
    ]

    # Retry mechanism with exponential backoff
    for attempt in range(1, retries + 1):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                temperature=temp,
                max_tokens=100
            )   
            output = str(response.choices[0].message.content)
            return output 

        except (openai.error.Timeout, openai.error.APIError, openai.error.RateLimitError) as e:
            print(f"Attempt {attempt} failed with error: {e}")
            
            if attempt < retries:
                # Exponential backoff
                sleep_time = backoff_factor * (2 ** (attempt - 1))
                print(f"Retrying in {sleep_time} seconds...")
                time.sleep(sleep_time)
            else:
                print(f"Failed after {retries} attempts.")
                return f"Error: {e}"

        except Exception as e:
            # Catch unexpected errors
            print(f"Unexpected error: {e}")
            return f"Unexpected Error: {e}"

### Importing the data

In [10]:
# df = pd.read_csv('/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/final_datasets/eng_gold_label_data.csv')
df = pd.read_csv('/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/dev_set_subs/eng_dev_subtask3.csv')

In [11]:
df.head()

             article_id                             dominant_narrative                                     sub_narratives                                               text
0  EN_UA_DEV_100012.txt          URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  Ukraine's Minerals: What the West is Fighting ...
1      EN_CC_200040.txt              CC: Criticism of climate movement                                               none  Climate Protesters Out Of Control As They Atta...
2      EN_CC_200070.txt  CC: Criticism of institutions and authorities  CC: Criticism of institutions and authorities:...  Wat? L.A. Mayor Garcetti Flies to Argentina to...
3  EN_UA_DEV_100034.txt                     URW: Overpraising the West  URW: Overpraising the West: The West belongs i...  Opinion: Restructuring Ukrainian debt is a ste...
4      EN_CC_200049.txt   CC: Questioning the measurements and science                                               none  Alarmists Warn of U.S. ‘Heat Dome’ Tied to Hum...

In [12]:
df['mode'] = df['dominant_narrative'].apply(lambda x: 'CC' if x.split(':')[0] == 'CC' else 'URW')

In [13]:
df['mode'].value_counts()

mode
CC     17
URW    13
Name: count, dtype: int64

In [14]:
df.head()

             article_id                             dominant_narrative                                     sub_narratives                                               text mode
0  EN_UA_DEV_100012.txt          URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  Ukraine's Minerals: What the West is Fighting ...  URW
1      EN_CC_200040.txt              CC: Criticism of climate movement                                               none  Climate Protesters Out Of Control As They Atta...   CC
2      EN_CC_200070.txt  CC: Criticism of institutions and authorities  CC: Criticism of institutions and authorities:...  Wat? L.A. Mayor Garcetti Flies to Argentina to...   CC
3  EN_UA_DEV_100034.txt                     URW: Overpraising the West  URW: Overpraising the West: The West belongs i...  Opinion: Restructuring Ukrainian debt is a ste...  URW
4      EN_CC_200049.txt   CC: Questioning the measurements and science                                               none  Alarmists Warn of U.S. ‘Heat Dome’ Tied to Hum...   CC

In [15]:
tqdm.pandas()

for temp in [0.3]:
    df[f'output_temp_{temp}'] = df.progress_apply(lambda x: generate_response(x['text'], x['dominant_narrative'], x['sub_narratives'], x['mode'], temp), axis=1)

  0%|          | 0/30 [00:00<?, ?it/s]

Document 1/21 added successfully.

  7%|▋         | 2/30 [00:10<02:21,  5.05s/it]

Document 1/27 added successfully.

 10%|█         | 3/30 [00:20<03:20,  7.41s/it]

Document 1/43 added successfully.

 13%|█▎        | 4/30 [00:35<04:25, 10.21s/it]

Document 1/66 added successfully.

 17%|█▋        | 5/30 [00:58<06:06, 14.65s/it]

Document 1/30 added successfully.

 20%|██        | 6/30 [01:10<05:30, 13.76s/it]

Document 1/61 added successfully.

 23%|██▎       | 7/30 [01:31<06:09, 16.05s/it]

Document 1/33 added successfully.

 27%|██▋       | 8/30 [01:44<05:30, 15.03s/it]

Document 1/15 added successfully.

 30%|███       | 9/30 [01:50<04:17, 12.26s/it]

Document 1/14 added successfully.

 33%|███▎      | 10/30 [01:56<03:26, 10.34s/it]

Document 1/38 added successfully.

 37%|███▋      | 11/30 [02:13<03:54, 12.37s/it]

Document 1/36 added successfully.

 40%|████      | 12/30 [02:29<04:00, 13.33s/it]

Document 1/29 added successfully.

 43%|████▎     | 13/30 [02:47<04:15, 15.04s/it]

Document 1/34 added successfully.

 47%|████▋     | 14/30 [03:02<03:57, 14.82s/it]

Document 1/26 added successfully.

 50%|█████     | 15/30 [03:12<03:22, 13.52s/it]

Document 1/48 added successfully.

 53%|█████▎    | 16/30 [03:31<03:33, 15.21s/it]

Document 1/71 added successfully.

 57%|█████▋    | 17/30 [03:58<04:00, 18.54s/it]

Document 1/22 added successfully.

 60%|██████    | 18/30 [04:07<03:09, 15.80s/it]

Document 1/39 added successfully.

 63%|██████▎   | 19/30 [04:23<02:54, 15.88s/it]

Document 1/26 added successfully.

 67%|██████▋   | 20/30 [04:34<02:22, 14.25s/it]

Document 1/25 added successfully.

 70%|███████   | 21/30 [04:47<02:06, 14.10s/it]

Document 1/48 added successfully.

 73%|███████▎  | 22/30 [05:06<02:04, 15.54s/it]

Document 1/17 added successfully.

 77%|███████▋  | 23/30 [05:14<01:32, 13.17s/it]

Document 1/17 added successfully.

 80%|████████  | 24/30 [05:22<01:08, 11.48s/it]

Document 1/16 added successfully.

 83%|████████▎ | 25/30 [05:29<00:51, 10.22s/it]

Document 1/11 added successfully.

 87%|████████▋ | 26/30 [05:34<00:34,  8.69s/it]

Document 1/15 added successfully.

 90%|█████████ | 27/30 [05:41<00:24,  8.12s/it]

Document 1/25 added successfully.

 93%|█████████▎| 28/30 [05:54<00:19,  9.75s/it]

Document 1/16 added successfully.

 97%|█████████▋| 29/30 [06:05<00:09,  9.91s/it]

Document 1/12 added successfully.

100%|██████████| 30/30 [06:11<00:00,  8.80s/it]

Document 1/28 added successfully.

100%|██████████| 30/30 [06:24<00:00, 12.81s/it]

In [16]:
# df.to_csv('SemEval 2025 Test Data/final_datasets/pred_eng_rag_gold_label_data.csv', index=False)
df.to_csv('/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/dev_set_subs/eng_dev_predictions(1).csv', index=False)

In [17]:
df.head()

         article_id                            dominant_narrative                                     sub_narratives                                       ground_truth                                               text mode                                    output_temp_0.3
0  EN_CC_100013.txt             CC: Criticism of climate movement  CC: Criticism of climate movement: Ad hominem ...  The text accuses climate activist Bill Gates f...  Bill Gates Says He Is ‘The Solution’ To Climat...   CC  The dominant narrative of "Criticism of climat...
1  EN_CC_200321.txt  CC: Questioning the measurements and science  CC: Questioning the measurements and science: ...  There are inconsistencies in the predictions o...  New paper makes ‘increasing tropical cyclone f...   CC  The dominant narrative of "Questioning the mea...
2  EN_CC_100005.txt             CC: Criticism of climate movement                                               none  The article talks about climate activists atta...  Climate Crazies Fail in Attempt to Vandalize A...   CC  The dominant narrative of "Criticism of climat...
3  EN_UA_014637.txt                 URW: Speculating war outcomes  URW: Speculating war outcomes: Russian army is...  The text conveys a narrative depicting negativ...  Putin’s masses of HIV-positive prisoners choos...  URW  The dominant narrative of "Speculating war out...
4  EN_UA_019640.txt                         URW: Praise of Russia  URW: Praise of Russia: Russia has internationa...  Multiple paragraphs within the text present al...  After North Korea’s Kim Jong Un, Putin and Xi ...  URW  The dominant narrative of "Praise of Russia" i...

In [18]:
from huggingface_hub import login

login("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")

from bert_score import score

for temp in [0.3]:
    predictions = df[f'output_temp_{temp}'].tolist()
    references = df['ground_truth'].tolist()

    P, R, F1 = score(predictions, references, lang="en")

    df[f'precision_{temp}'] = P.tolist()
    df[f'recall_{temp}'] = R.tolist()
    df[f'f1_{temp}'] = F1.tolist()

/Users/rahulbouri/miniconda3/envs/sem-eval/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /Users/rahulbouri/.cache/huggingface/token
Login successful

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [19]:
df.head()

         article_id                            dominant_narrative                                     sub_narratives                                       ground_truth                                               text mode                                    output_temp_0.3  precision_0.3  recall_0.3    f1_0.3
0  EN_CC_100013.txt             CC: Criticism of climate movement  CC: Criticism of climate movement: Ad hominem ...  The text accuses climate activist Bill Gates f...  Bill Gates Says He Is ‘The Solution’ To Climat...   CC  The dominant narrative of "Criticism of climat...       0.840746    0.892593  0.865894
1  EN_CC_200321.txt  CC: Questioning the measurements and science  CC: Questioning the measurements and science: ...  There are inconsistencies in the predictions o...  New paper makes ‘increasing tropical cyclone f...   CC  The dominant narrative of "Questioning the mea...       0.842786    0.892309  0.866841
2  EN_CC_100005.txt             CC: Criticism of climate movement                                               none  The article talks about climate activists atta...  Climate Crazies Fail in Attempt to Vandalize A...   CC  The dominant narrative of "Criticism of climat...       0.862852    0.871261  0.867036
3  EN_UA_014637.txt                 URW: Speculating war outcomes  URW: Speculating war outcomes: Russian army is...  The text conveys a narrative depicting negativ...  Putin’s masses of HIV-positive prisoners choos...  URW  The dominant narrative of "Speculating war out...       0.858410    0.885847  0.871912
4  EN_UA_019640.txt                         URW: Praise of Russia  URW: Praise of Russia: Russia has internationa...  Multiple paragraphs within the text present al...  After North Korea’s Kim Jong Un, Putin and Xi ...  URW  The dominant narrative of "Praise of Russia" i...       0.851072    0.840228  0.845615

In [20]:
df.to_csv('SemEval 2025 Test Data/final_datasets/pred_eng_rag_gold_label_data.csv', index=False)

In [21]:
# print(f"Mean Precision Temp 0.2: {df['precision_0.2'].mean()}")
# print(f"Mean Recall Temp 0.2: {df['recall_0.2'].mean()}")
# print(f"Mean F1 Temp 0.2: {df['f1_0.2'].mean()}")
# print()
print(f"Mean Precision Temp 0.3: {df['precision_0.3'].mean()}")
print(f"Mean Recall Temp 0.3: {df['recall_0.3'].mean()}")
print(f"Mean F1 Temp 0.3: {df['f1_0.3'].mean()}")
print()
# print(f"Mean Precision Temp 0.4: {df['precision_0.4'].mean()}")
# print(f"Mean Recall Temp 0.4: {df['recall_0.4'].mean()}")
# print(f"Mean F1 Temp 0.4: {df['f1_0.4'].mean()}")
# print()

Mean Precision Temp 0.3: 0.8408007483764235
Mean Recall Temp 0.3: 0.8709640614504884
Mean F1 Temp 0.3: 0.8555465014697295

In [22]:
df.head()

         article_id                            dominant_narrative                                     sub_narratives                                       ground_truth                                               text mode                                    output_temp_0.3  precision_0.3  recall_0.3    f1_0.3
0  EN_CC_100013.txt             CC: Criticism of climate movement  CC: Criticism of climate movement: Ad hominem ...  The text accuses climate activist Bill Gates f...  Bill Gates Says He Is ‘The Solution’ To Climat...   CC  The dominant narrative of "Criticism of climat...       0.840746    0.892593  0.865894
1  EN_CC_200321.txt  CC: Questioning the measurements and science  CC: Questioning the measurements and science: ...  There are inconsistencies in the predictions o...  New paper makes ‘increasing tropical cyclone f...   CC  The dominant narrative of "Questioning the mea...       0.842786    0.892309  0.866841
2  EN_CC_100005.txt             CC: Criticism of climate movement                                               none  The article talks about climate activists atta...  Climate Crazies Fail in Attempt to Vandalize A...   CC  The dominant narrative of "Criticism of climat...       0.862852    0.871261  0.867036
3  EN_UA_014637.txt                 URW: Speculating war outcomes  URW: Speculating war outcomes: Russian army is...  The text conveys a narrative depicting negativ...  Putin’s masses of HIV-positive prisoners choos...  URW  The dominant narrative of "Speculating war out...       0.858410    0.885847  0.871912
4  EN_UA_019640.txt                         URW: Praise of Russia  URW: Praise of Russia: Russia has internationa...  Multiple paragraphs within the text present al...  After North Korea’s Kim Jong Un, Putin and Xi ...  URW  The dominant narrative of "Praise of Russia" i...       0.851072    0.840228  0.845615