In [1]:
import os
import ast
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.width', 1000)

from tqdm import tqdm

from openai import AzureOpenAI

pd.set_option('display.max_columns', 100)

### Load OpenAI Model

In [2]:
os.environ["AZURE_OPENAI_KEY"] = ""
os.environ["AZURE_OPENAI_ENDPOINT"] = ""
os.environ["AZURE_API_VERSION"] = ""
os.environ["AZURE_DEPLOYMENT_ID"] = ""
os.environ["AWS_ACCESS_KEY"] = ""
os.environ["AWS_SECRET_KEY"] = ""
os.environ["AWS_SESSION_TOKEN"] = ""
model_name = "gpt-4o-mini"

client = AzureOpenAI(
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_KEY"),
    api_version=os.getenv("AZURE_API_VERSION"),
    azure_deployment=os.getenv("AZURE_DEPLOYMENT_ID")
)

### Taxonomy Functions

In [3]:
def clean_and_parse(x):
    import ast 

    if isinstance(x, str) and x.startswith('[') and x.endswith(']'):
        cleaned = x.replace('""', '"')
        cleaned = cleaned.replace('\n', ' ').replace('\r', '')  # Remove line breaks, if any

        try:
            return ast.literal_eval(cleaned)
        except Exception as e:
            print(f"Error parsing string: {cleaned}\n{e}")
            return x
    else:
        return x

def get_main_taxonomy_examples(dom: str, mode: str) -> str:

    if mode == "CC":
    
        df = pd.read_csv("../semeval-task-10/cc_taxonomy.csv")
        df = df.astype(str)
        df['Main Narrative Example'] = df['Main Narrative Example'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') and x.endswith(']') else x)
                
        taxonomy = ''
        examples = ''

        dom = dom.split(":")[0] if len(dom.split(":")) > 0 else dom

        if dom in df['Main Narrative'].values:
            temp = df[df['Main Narrative'] == dom].reset_index()         
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Main Narrative']} | Definition: {temp.loc[0, 'Main Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Main Narrative Example'], list):
                for item in temp.loc[0, 'Main Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Main Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Main Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Main Narrative']}\n"
            else:
                pass


        return (taxonomy, examples)

    else:

        df = pd.read_csv("../semeval-task-10/urw_taxonomy.csv")
        df = df.astype(str)
        df['Main Narrative Example'] = df['Main Narrative Example'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') and x.endswith(']') else x)
          
        taxonomy = ''
        examples = ''

        dom = dom.split(":")[0] if len(dom.split(":")) > 0 else dom

        if dom in df['Main Narrative'].values:
            temp = df[df['Main Narrative'] == dom].reset_index()           
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Main Narrative']} | Definition: {temp.loc[0, 'Main Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Main Narrative Example'], list):
                for item in temp.loc[0, 'Main Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Main Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Main Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Main Narrative']}\n"
            else:
                pass
            
        return (taxonomy, examples)

def get_sub_taxonomy_examples(sub: str, mode: str) -> str:

    if mode == "CC":
        df = pd.read_csv("../semeval-task-10/cc_taxonomy.csv")
        df = df.astype(str)
        df['Sub Narrative Example'] = df['Sub Narrative Example'].apply(clean_and_parse)

        taxonomy = ''
        examples = ''

        sub = sub.split(":")[2][1:] if len(sub.split(":")) > 1 else sub

        if sub in df['Sub Narrative'].values:
            temp = df[df['Sub Narrative'] == sub].reset_index()
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Sub Narrative']} | Definition: {temp.loc[0, 'Sub Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Sub Narrative Example'], list):
                for item in temp.loc[0, 'Sub Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Sub Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Sub Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Sub Narrative']}\n"
            else:
                pass
        return (taxonomy, examples)

    else:
        df = pd.read_csv("../semeval-task-10/urw_taxonomy.csv")
        df = df.astype(str)
        df['Sub Narrative Example'] = df['Sub Narrative Example'].apply(clean_and_parse)

        taxonomy = ''
        examples = ''

        sub = sub.split(":")[2][1:] if len(sub.split(":")) > 1 else sub

        if sub in df['Sub Narrative'].values:
            temp = df[df['Sub Narrative'] == sub].reset_index()
            taxonomy = taxonomy + f"Category: {temp.loc[0, 'Sub Narrative']} | Definition: {temp.loc[0, 'Sub Narrative Definition']}\n"
            if isinstance(temp.loc[0, 'Sub Narrative Example'], list):
                for item in temp.loc[0, 'Sub Narrative Example']:
                    examples = examples + f"{item} => {temp.loc[0, 'Sub Narrative']}\n"
                if not temp.loc[0, 'Detail Instructions Sub Narrative'] == 'nan':
                    examples = examples + f"Note: {temp.loc[0, 'Detail Instructions Sub Narrative']}\n"
            else:
                pass
        return (taxonomy, examples)

In [4]:
def create_prompt(text, dom, sub, mode):
    # Helper function replacing quotation marks in the text:
    replace_qm = lambda s: s.replace('"', "'")

    language = 'HINDI'

    if mode == "CC":
        # Update predicted_labels by slicing from the 4th character
        main_taxonomy, main_examples = get_main_taxonomy_examples(dom, mode)
        sub_taxonomy, sub_examples = get_sub_taxonomy_examples(sub, mode)
        context = f"""You will be given an article along with the dominant narrative and sub narrative associated with the article. 
        
        GOAL: Justify the choice of dominant and sub narratives assigned to the article in {language}. Provide reasoning and quote relevant text from the original text as to why these are the correct choice of dominant and sub narratives for the text file.

            INSTRUCTIONS:
            Read the provided text carefully.
            You will be given: 
            1.Taxonomy - definition of the narrative
            2.List of relevant examples - sentences which determine which justify the narrative and align with its defintion 
            3.Any additional idenyifying information for the narratives.
            Based on the given information give an explanation as to why the dominant and sub narratives are the correct choice for the text file.
            
            Note: Keep the output concise and to the point - ideally find relevant textual examples.

            DOMINANT NARRATIVE: {dom[4:]}
            TAXONOMY: {main_taxonomy}
            RELEVANT EXAMPLES: 
            {main_examples}

            SUB NARRATIVE: {sub[4:]}
            TAXONOMY: {sub_taxonomy}
            RELEVANT EXAMPLES:
            {sub_examples}
        """

        prompt = f'''{context}
        -------------------------------------------------------
        Based on the given Instructions, Taxonomies and Examples: Justify the choice of dominant and sub narratives assigned to the Climate Change article in {language} within 80 words.

        ARTICLE TEXT TO PREDICT: "{replace_qm(text)}" => '''
        
        return {
            "role": "user",
            "content": prompt
        }
        
    else:
        # Update predicted_labels by slicing from the 5th character
        main_taxonomy, main_examples = get_main_taxonomy_examples(dom, mode)
        sub_taxonomy, sub_examples = get_sub_taxonomy_examples(sub, mode)

        context = f"""You will be given an article along with the dominant narrative and sub narrative associated with the article. 
        
        GOAL: Justify the choice of dominant and sub narratives assigned to the article in {language}. Provide reasoning and quote relevant text from the original text as to why these are the correct choice of dominant and sub narratives for the text file.

            INSTRUCTIONS:
            Read the provided text carefully.
            You will be given: 
            1.Taxonomy - definition of the narrative
            2.List of relevant examples - sentences which determine which justify the narrative and align with its defintion 
            3.Any additional idenyifying information for the narratives.
            Based on the given information give an explanation as to why the dominant and sub narratives are the correct choice for the text file.
            
            Note: Keep the output concise and to the point - ideally find relevant textual examples.

            DOMINANT NARRATIVE: {dom[4:]}
            TAXONOMY: {main_taxonomy}
            RELEVANT EXAMPLES: 
            {main_examples}

            SUB NARRATIVE: {sub[4:]}
            TAXONOMY: {sub_taxonomy}
            RELEVANT EXAMPLES:
            {sub_examples}
        """

        prompt = f'''{context}
        -------------------------------------------------------
        Based on the given Instructions, Taxonomies and Examples: Justify the choice of dominant and sub narratives assigned to the Climate Change article in {language} within 80 words.

        ARTICLE TEXT TO PREDICT: "{replace_qm(text)}" => '''
        
        return {
            "role": "user",
            "content": prompt
        }

In [5]:
def get_embedded_json(embedded_str):
    import re
    try:
        # Extract only the list content using regex
        match = re.search(r"\[.*\]", embedded_str)
        if not match:
            return []  # Return empty list if no valid list is found
        
        cleaned_str = match.group(0)  # Extract the matched list portion

        # Convert to Python list safely
        return ast.literal_eval(cleaned_str)
    
    except (ValueError, SyntaxError):
        return []  # Return empty list if parsing fails

In [6]:
def generate_response(text:str, dom, sub, mode, temp):

    language = 'HINDI'

    system_main = \
'''You are an expert trained to analyse and justify the choice of dominant and sub narratives assigned to a given article within 80 words.

Instructions:

Write in {language} only.
Use ReACT (Reasoning and Contextual Text) to justify the choice of dominant and sub narratives assigned to the article.
Provide reasoning and quote relevant text from the original text as to why these are the correct choice of dominant and sub narratives for the text file.
Keep the output concise and to the point—ideally find relevant textual examples.

Categorization Rules:

Use the help of the provided taxonomy and examples to justify the choice of dominant and sub narratives assigned to the article.

OUTPUT FORMAT:
Return {language} language text in paragraph(s) format within 80 words.
'''

    
    prompt = create_prompt(text, dom, sub, mode)

    messages = [
        {"role": "system", "content": system_main},
        {"role": "user", "content": prompt.get("content", "")}
    ]
    
    response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=messages,
    temperature=temp,
    max_tokens=100
    )   

    output = str(response.choices[0].message.content)
    return output

### Importing the data

In [7]:
df = pd.read_csv('/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/dev_set_subs/hindi_dev_subtask3.csv')

In [8]:
df.shape

(29, 4)

In [9]:
df.head()

   article_id                                 dominant_narrative                                     sub_narratives                                               text
0   HI_26.txt                              URW: Praise of Russia                                               none  - Hindi News\n- International\n- PM Modi LIVE ...
1  HI_160.txt  URW: Blaming the war on others rather than the...  URW: Blaming the war on others rather than the...  Russia Ukraine War: जब यूक्रेन नहीं सदस्य देश,...
2   HI_51.txt              URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  रूस-यूक्रेन युद्ध के दो साल: क्या भारत की विदे...
3  HI_114.txt                  URW: Amplifying war-related fears  URW: Amplifying war-related fears: By continui...  रूस की इस हरकत से छिड़ जाएगा विश्व युद्ध? आगबब...
4  HI_152.txt                              URW: Praise of Russia  URW: Praise of Russia: Russia has internationa...  दक्षिण कोरिया के रक्षा मंत्री का बड़ा आरोप, Ru...

In [10]:
df['mode'] = df['dominant_narrative'].apply(lambda x: 'CC' if x.split(':')[0] == 'CC' else 'URW')

In [11]:
df['mode'].value_counts()

mode
URW    25
CC      4
Name: count, dtype: int64

In [12]:
df.head()

   article_id                                 dominant_narrative                                     sub_narratives                                               text mode
0   HI_26.txt                              URW: Praise of Russia                                               none  - Hindi News\n- International\n- PM Modi LIVE ...  URW
1  HI_160.txt  URW: Blaming the war on others rather than the...  URW: Blaming the war on others rather than the...  Russia Ukraine War: जब यूक्रेन नहीं सदस्य देश,...  URW
2   HI_51.txt              URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  रूस-यूक्रेन युद्ध के दो साल: क्या भारत की विदे...  URW
3  HI_114.txt                  URW: Amplifying war-related fears  URW: Amplifying war-related fears: By continui...  रूस की इस हरकत से छिड़ जाएगा विश्व युद्ध? आगबब...  URW
4  HI_152.txt                              URW: Praise of Russia  URW: Praise of Russia: Russia has internationa...  दक्षिण कोरिया के रक्षा मंत्री का बड़ा आरोप, Ru...  URW

In [13]:
tqdm.pandas()

for temp in [0.3]:
    df[f'output_temp_{temp}'] = df.progress_apply(lambda x: generate_response(x['text'], x['dominant_narrative'], x['sub_narratives'], x['mode'], temp), axis=1)

100%|██████████| 29/29 [00:47<00:00,  1.65s/it]

In [14]:
df.to_csv('/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/dev_set_subs/hindi_dev_predictions.csv', index=False)

In [15]:
df.head()

   article_id                                 dominant_narrative                                     sub_narratives                                               text mode                                    output_temp_0.3
0   HI_26.txt                              URW: Praise of Russia                                               none  - Hindi News\n- International\n- PM Modi LIVE ...  URW  इस लेख में "रूस की प्रशंसा" को प्रमुख कथा के र...
1  HI_160.txt  URW: Blaming the war on others rather than the...  URW: Blaming the war on others rather than the...  Russia Ukraine War: जब यूक्रेन नहीं सदस्य देश,...  URW  इस लेख में प्रमुख कथा "युद्ध का दोष दूसरों पर ...
2   HI_51.txt              URW: Discrediting the West, Diplomacy  URW: Discrediting the West, Diplomacy: The Wes...  रूस-यूक्रेन युद्ध के दो साल: क्या भारत की विदे...  URW  इस लेख में प्रमुख कथा "पश्चिम का अपमान" और उपक...
3  HI_114.txt                  URW: Amplifying war-related fears  URW: Amplifying war-related fears: By continui...  रूस की इस हरकत से छिड़ जाएगा विश्व युद्ध? आगबब...  URW  इस लेख का प्रमुख नरेटिव "युद्ध से संबंधित भय क...
4  HI_152.txt                              URW: Praise of Russia  URW: Praise of Russia: Russia has internationa...  दक्षिण कोरिया के रक्षा मंत्री का बड़ा आरोप, Ru...  URW  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...

In [17]:
from huggingface_hub import login

login("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")

from bert_score import score

for i in tqdm(np.arange(0.1, 1, 0.1)):
    temp = round(i, 2)
    predictions = df[f'output_temp_{temp}'].tolist()
    references = df['ground_truth'].tolist()

    P, R, F1 = score(predictions, references, lang="en")

    df[f'precision_{temp}'] = P.tolist()
    df[f'recall_{temp}'] = R.tolist()
    df[f'f1_{temp}'] = F1.tolist()

/Users/rahulbouri/miniconda3/envs/sem-eval/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /Users/rahulbouri/.cache/huggingface/token
Login successful

  0%|          | 0/9 [00:00<?, ?it/s]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 11%|█         | 1/9 [02:45<22:04, 165.57s/it]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 22%|██▏       | 2/9 [05:26<18:58, 162.64s/it]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 33%|███▎      | 3/9 [08:14<16:30, 165.15s/it]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 44%|████▍     | 4/9 [10:50<13:28, 161.69s/it]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 56%|█████▌    | 5/9 [13:22<10:32, 158.07s/it]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 67%|██████▋   | 6/9 [16:23<08:17, 165.78s/it]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 78%|███████▊  | 7/9 [19:16<05:36, 168.28s/it]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 89%|████████▉ | 8/9 [21:57<02:46, 166.06s/it]Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
100%|██████████| 9/9 [25:04<00:00, 167.20s/it]

In [18]:
df.head()

   article_id                 dominant_narrative                                     sub_narratives                                       ground_truth                                               text mode                                    output_temp_0.1                                    output_temp_0.2                                    output_temp_0.3                                    output_temp_0.4                                    output_temp_0.5                                    output_temp_0.6                                    output_temp_0.7                                    output_temp_0.8                                    output_temp_0.9  precision_0.1  recall_0.1    f1_0.1  precision_0.2  recall_0.2    f1_0.2  precision_0.3  recall_0.3    f1_0.3  precision_0.4  recall_0.4    f1_0.4  precision_0.5  recall_0.5    f1_0.5  precision_0.6  recall_0.6    f1_0.6  precision_0.7  recall_0.7    f1_0.7  precision_0.8  recall_0.8    f1_0.8  precision_0.9  recall_0.9    f1_0.9
0  HI_368.txt  URW: Amplifying war-related fears  URW: Amplifying war-related fears: There is a ...  इस लेख का प्रमुख आख्यान युद्ध में इस्तेमाल किए...  बाइडन के कदम से भड़के पुतिन, न्यूक्लियर डॉक्ट्...  URW  इस लेख में प्रमुख कथा "युद्ध से संबंधित भय को ...  इस लेख में प्रमुख कथा "युद्ध से संबंधित भय को ...  इस लेख का प्रमुख नैरेटर "युद्ध से संबंधित भय क...  इस लेख में "युद्ध से संबंधित भय को बढ़ाना" मुख...  इस लेख में प्रमुख कथा "युद्ध से संबंधित भय को ...  इस लेख में प्रमुख कथा "युद्ध से संबंधित डर को ...  इस लेख के लिए प्रमुख कथा "युद्ध से संबंधित भय ...  इस लेख में "युद्ध से संबंधित डर को बढ़ाना" मुख...  यह लेख "युद्ध से संबंधित भय को बढ़ाना" की प्रम...       0.929886    0.935634  0.932751       0.933695    0.938665  0.936174       0.932991    0.934491  0.933740       0.933390    0.935667  0.934527       0.932170    0.936790  0.934474       0.936718    0.939321  0.938018       0.933884    0.938083  0.935979       0.933010    0.933508  0.933259       0.934393    0.937430  0.935909
1  HI_191.txt              URW: Praise of Russia  URW: Praise of Russia: Praise of Russian Presi...  यह परियोजना स्पष्ट रूप से रूसी राष्ट्रपति पुति...  G20 से दूर रहे पुतिन ने की मोदी की तारीफ, रूस ...  URW  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...  इस लेख में प्रमुख नरेटिव "रूस की प्रशंसा" है क...  इस लेख में प्रमुख कथानक "रूस की प्रशंसा" और उप...  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...  इस लेख में मुख्य रूप से "रूस की प्रशंसा" और उप...  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है क्यो...  यह लेख "रूस की प्रशंसा" के प्रमुख नैरेटिव को द...       0.916243    0.939891  0.927916       0.916371    0.938935  0.927516       0.916243    0.939891  0.927916       0.911666    0.939811  0.925525       0.918132    0.944702  0.931228       0.913423    0.937559  0.925333       0.923006    0.947054  0.934876       0.908455    0.932221  0.920185       0.916641    0.938251  0.927320
2  HI_112.txt          URW: Russia is the Victim  URW: Russia is the Victim: Russia actions in U...  इस रिपोर्ट में कुर्स्क पर यूक्रेनी सेना के हमल...  टैंकों और बख्तरबंद वाहनों के साथ रूसी इलाके मे...  URW  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में प्रमुख कथा "रूस पीड़ित है" और उपकथा...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में "रूस victim है" और "रूस का कार्य के...  इस लेख में "रूस पीड़ित है" को प्रमुख कथा के रू...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में प्रमुख कथा "रूस पीड़ित है" और उप-कथ...  रूस को पीड़ित के रूप में वर्णित करना और उसके य...       0.923104    0.926454  0.924776       0.922785    0.923695  0.923240       0.927819    0.927589  0.927704       0.923219    0.923373  0.923296       0.927509    0.928853  0.928181       0.923133    0.920989  0.922060       0.924546    0.926771  0.925657       0.927413    0.926081  0.926746       0.933375    0.931024  0.932198
3    HI_2.txt          URW: Russia is the Victim  URW: Russia is the Victim: The West is russoph...  इस लेख का मुख्य आख्यान यह है कि पश्चिम किस प्र...  प्रधानमंत्री नरेंद्र मोदी की 8 और 9 जुलाई को अ...  URW  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में "रूस पीड़ित है" को प्रमुख कथा के रू...  इस लेख में "रूस पीड़ित है" को मुख्य कथा के रूप...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख का प्रमुख नरेटिव "रूस पीड़ित है" है, क्...  इस लेख में "रूस पीड़ित है" को प्रमुख कथा के रू...  प्रस्तावित लेख में प्रमुख कथा "रूस पीड़ित है" ...  लेख का प्रमुख नैरेटीव "रूस पीड़ित है" है, क्यो...       0.916464    0.933824  0.925063       0.914696    0.932073  0.923303       0.908423    0.928358  0.918283       0.914628    0.933801  0.924115       0.905411    0.921520  0.913395       0.914112    0.934655  0.924269       0.920914    0.938883  0.929812       0.899354    0.919136  0.909137       0.902060    0.922728  0.912277
4  HI_279.txt      URW: Speculating war outcomes                                               none  इस रिपोर्ट का मुख्य उद्देश्य पश्चिम के युद्ध प...  पुतिन की धमकी के बाद लंबी दूरी की मिसाइलों पर ...  URW  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों की ...  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों की ...  इस लेख का प्रमुख कथानक "युद्ध के परिणामों का अ...  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों का ...  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों की ...  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों की ...  इस लेख में प्रमुख narritive "युद्ध के परिणामों...  इस लेख का प्रमुख कथा "युद्ध के परिणामों का अनु...  इस लेख में प्रमुख कथा "युद्ध के परिणामों की भव...       0.932485    0.931811  0.932148       0.927331    0.928700  0.928015       0.932154    0.931566  0.931860       0.934078    0.932492  0.933284       0.929994    0.926533  0.928260       0.930733    0.927510  0.929119       0.925859    0.928547  0.927201       0.928653    0.930528  0.929590       0.928338    0.926201  0.927268

In [19]:
df.to_csv('SemEval 2025 Test Data/final_datasets/pred_hindi_gold_label_data.csv', index=False)

In [20]:
print(f"Mean Precision Temp 0.1: {df['precision_0.1'].mean()}")
print(f"Mean Recall Temp 0.1: {df['recall_0.1'].mean()}")
print(f"Mean F1 Temp 0.1: {df['f1_0.1'].mean()}")
print()
print(f"Mean Precision Temp 0.2: {df['precision_0.2'].mean()}")
print(f"Mean Recall Temp 0.2: {df['recall_0.2'].mean()}")
print(f"Mean F1 Temp 0.2: {df['f1_0.2'].mean()}")
print()
print(f"Mean Precision Temp 0.3: {df['precision_0.3'].mean()}")
print(f"Mean Recall Temp 0.3: {df['recall_0.3'].mean()}")
print(f"Mean F1 Temp 0.3: {df['f1_0.3'].mean()}")
print()
print(f"Mean Precision Temp 0.4: {df['precision_0.4'].mean()}")
print(f"Mean Recall Temp 0.4: {df['recall_0.4'].mean()}")
print(f"Mean F1 Temp 0.4: {df['f1_0.4'].mean()}")
print()
print(f"Mean Precision Temp 0.5: {df['precision_0.5'].mean()}")
print(f"Mean Recall Temp 0.5: {df['recall_0.5'].mean()}")
print(f"Mean F1 Temp 0.5: {df['f1_0.5'].mean()}")
print()
print(f"Mean Precision Temp 0.6: {df['precision_0.6'].mean()}")
print(f"Mean Recall Temp 0.6: {df['recall_0.6'].mean()}")
print(f"Mean F1 Temp 0.6: {df['f1_0.6'].mean()}")
print()
print(f"Mean Precision Temp 0.7: {df['precision_0.7'].mean()}")
print(f"Mean Recall Temp 0.7: {df['recall_0.7'].mean()}")
print(f"Mean F1 Temp 0.7: {df['f1_0.7'].mean()}")
print()
print(f"Mean Precision Temp 0.8: {df['precision_0.8'].mean()}")
print(f"Mean Recall Temp 0.8: {df['recall_0.8'].mean()}")
print(f"Mean F1 Temp 0.8: {df['f1_0.8'].mean()}")
print()
print(f"Mean Precision Temp 0.9: {df['precision_0.9'].mean()}")
print(f"Mean Recall Temp 0.9: {df['recall_0.9'].mean()}")
print(f"Mean F1 Temp 0.9: {df['f1_0.9'].mean()}")

Mean Precision Temp 0.1: 0.9147929484362429
Mean Recall Temp 0.1: 0.9283676592179531
Mean F1 Temp 0.1: 0.9214361300740217

Mean Precision Temp 0.2: 0.9150652258507328
Mean Recall Temp 0.2: 0.928614518494186
Mean F1 Temp 0.2: 0.9216963815565554

Mean Precision Temp 0.3: 0.9150996183484329
Mean Recall Temp 0.3: 0.9286445227929347
Mean F1 Temp 0.3: 0.9217267882638644

Mean Precision Temp 0.4: 0.9153432355025889
Mean Recall Temp 0.4: 0.9287550458636309
Mean F1 Temp 0.4: 0.9219067167741647

Mean Precision Temp 0.5: 0.9153574260405308
Mean Recall Temp 0.5: 0.928554038000848
Mean F1 Temp 0.5: 0.9218138162953866

Mean Precision Temp 0.6: 0.915193368116191
Mean Recall Temp 0.6: 0.9287843089647244
Mean F1 Temp 0.6: 0.9218256782373616

Mean Precision Temp 0.7: 0.9154110986334054
Mean Recall Temp 0.7: 0.9289237211405305
Mean F1 Temp 0.7: 0.9220096644959919

Mean Precision Temp 0.8: 0.9148050281050292
Mean Recall Temp 0.8: 0.9281715787754158
Mean F1 Temp 0.8: 0.9213383247197601

Mean Precision Temp 0.9: 0.9150411539127172
Mean Recall Temp 0.9: 0.9285821642900378
Mean F1 Temp 0.9: 0.9216684189485145

In [23]:
df.head()

   article_id                 dominant_narrative                                     sub_narratives                                       ground_truth                                               text mode                                    output_temp_0.1                                    output_temp_0.2                                    output_temp_0.3                                    output_temp_0.4                                    output_temp_0.5                                    output_temp_0.6                                    output_temp_0.7                                    output_temp_0.8                                    output_temp_0.9  precision_0.1  recall_0.1    f1_0.1  precision_0.2  recall_0.2    f1_0.2  precision_0.3  recall_0.3    f1_0.3  precision_0.4  recall_0.4    f1_0.4  precision_0.5  recall_0.5    f1_0.5  precision_0.6  recall_0.6    f1_0.6  precision_0.7  recall_0.7    f1_0.7  precision_0.8  recall_0.8    f1_0.8  precision_0.9  recall_0.9    f1_0.9
0  HI_368.txt  URW: Amplifying war-related fears  URW: Amplifying war-related fears: There is a ...  इस लेख का प्रमुख आख्यान युद्ध में इस्तेमाल किए...  बाइडन के कदम से भड़के पुतिन, न्यूक्लियर डॉक्ट्...  URW  इस लेख में प्रमुख कथा "युद्ध से संबंधित भय को ...  इस लेख में प्रमुख कथा "युद्ध से संबंधित भय को ...  इस लेख का प्रमुख नैरेटर "युद्ध से संबंधित भय क...  इस लेख में "युद्ध से संबंधित भय को बढ़ाना" मुख...  इस लेख में प्रमुख कथा "युद्ध से संबंधित भय को ...  इस लेख में प्रमुख कथा "युद्ध से संबंधित डर को ...  इस लेख के लिए प्रमुख कथा "युद्ध से संबंधित भय ...  इस लेख में "युद्ध से संबंधित डर को बढ़ाना" मुख...  यह लेख "युद्ध से संबंधित भय को बढ़ाना" की प्रम...       0.929886    0.935634  0.932751       0.933695    0.938665  0.936174       0.932991    0.934491  0.933740       0.933390    0.935667  0.934527       0.932170    0.936790  0.934474       0.936718    0.939321  0.938018       0.933884    0.938083  0.935979       0.933010    0.933508  0.933259       0.934393    0.937430  0.935909
1  HI_191.txt              URW: Praise of Russia  URW: Praise of Russia: Praise of Russian Presi...  यह परियोजना स्पष्ट रूप से रूसी राष्ट्रपति पुति...  G20 से दूर रहे पुतिन ने की मोदी की तारीफ, रूस ...  URW  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...  इस लेख में प्रमुख नरेटिव "रूस की प्रशंसा" है क...  इस लेख में प्रमुख कथानक "रूस की प्रशंसा" और उप...  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है, क्य...  इस लेख में मुख्य रूप से "रूस की प्रशंसा" और उप...  इस लेख में प्रमुख कथा "रूस की प्रशंसा" है क्यो...  यह लेख "रूस की प्रशंसा" के प्रमुख नैरेटिव को द...       0.916243    0.939891  0.927916       0.916371    0.938935  0.927516       0.916243    0.939891  0.927916       0.911666    0.939811  0.925525       0.918132    0.944702  0.931228       0.913423    0.937559  0.925333       0.923006    0.947054  0.934876       0.908455    0.932221  0.920185       0.916641    0.938251  0.927320
2  HI_112.txt          URW: Russia is the Victim  URW: Russia is the Victim: Russia actions in U...  इस रिपोर्ट में कुर्स्क पर यूक्रेनी सेना के हमल...  टैंकों और बख्तरबंद वाहनों के साथ रूसी इलाके मे...  URW  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में प्रमुख कथा "रूस पीड़ित है" और उपकथा...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में "रूस victim है" और "रूस का कार्य के...  इस लेख में "रूस पीड़ित है" को प्रमुख कथा के रू...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में प्रमुख कथा "रूस पीड़ित है" और उप-कथ...  रूस को पीड़ित के रूप में वर्णित करना और उसके य...       0.923104    0.926454  0.924776       0.922785    0.923695  0.923240       0.927819    0.927589  0.927704       0.923219    0.923373  0.923296       0.927509    0.928853  0.928181       0.923133    0.920989  0.922060       0.924546    0.926771  0.925657       0.927413    0.926081  0.926746       0.933375    0.931024  0.932198
3    HI_2.txt          URW: Russia is the Victim  URW: Russia is the Victim: The West is russoph...  इस लेख का मुख्य आख्यान यह है कि पश्चिम किस प्र...  प्रधानमंत्री नरेंद्र मोदी की 8 और 9 जुलाई को अ...  URW  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख में "रूस पीड़ित है" को प्रमुख कथा के रू...  इस लेख में "रूस पीड़ित है" को मुख्य कथा के रूप...  इस लेख में प्रमुख कथा "रूस पीड़ित है" है, क्यो...  इस लेख का प्रमुख नरेटिव "रूस पीड़ित है" है, क्...  इस लेख में "रूस पीड़ित है" को प्रमुख कथा के रू...  प्रस्तावित लेख में प्रमुख कथा "रूस पीड़ित है" ...  लेख का प्रमुख नैरेटीव "रूस पीड़ित है" है, क्यो...       0.916464    0.933824  0.925063       0.914696    0.932073  0.923303       0.908423    0.928358  0.918283       0.914628    0.933801  0.924115       0.905411    0.921520  0.913395       0.914112    0.934655  0.924269       0.920914    0.938883  0.929812       0.899354    0.919136  0.909137       0.902060    0.922728  0.912277
4  HI_279.txt      URW: Speculating war outcomes                                               none  इस रिपोर्ट का मुख्य उद्देश्य पश्चिम के युद्ध प...  पुतिन की धमकी के बाद लंबी दूरी की मिसाइलों पर ...  URW  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों की ...  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों की ...  इस लेख का प्रमुख कथानक "युद्ध के परिणामों का अ...  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों का ...  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों की ...  इस लेख का प्रमुख नरेटिव "युद्ध के परिणामों की ...  इस लेख में प्रमुख narritive "युद्ध के परिणामों...  इस लेख का प्रमुख कथा "युद्ध के परिणामों का अनु...  इस लेख में प्रमुख कथा "युद्ध के परिणामों की भव...       0.932485    0.931811  0.932148       0.927331    0.928700  0.928015       0.932154    0.931566  0.931860       0.934078    0.932492  0.933284       0.929994    0.926533  0.928260       0.930733    0.927510  0.929119       0.925859    0.928547  0.927201       0.928653    0.930528  0.929590       0.928338    0.926201  0.927268